spring:
    application:
        name: message
    data:
        mongodb:
        host: localhost
        port: 27017
        database: tchat-message
        auto-index-creation: true

server:
    port: 8083

logging:
    level:
        com.tchat.auth: DEBUG